[package]
name = "d13"
version = "0.1.0"
authors = ["Blair Mitchelmore <blair@mitchelmore.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
